ball: fin.c 
	gcc -lm -O3 -ggdb3 fin.c -o ball
	# valgrind --leak-check=full \
        #  --show-leak-kinds=all \
        # --track-origins=yes \
        #  --verbose \
        #  --log-file=valgrind-out.txt \
         ./ball

